// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMkciS7UKqhrKY6fOfpzaqAzjG-WG_zBE',
    appId: '1:248257115153:web:c3578c40c00f3f18722db0',
    messagingSenderId: '248257115153',
    projectId: 'mechclient-bea53',
    authDomain: 'mechclient-bea53.firebaseapp.com',
    databaseURL: 'https://mechclient-bea53-default-rtdb.firebaseio.com',
    storageBucket: 'mechclient-bea53.appspot.com',
    measurementId: 'G-2Y0EH00012',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM8HaNb6gm0bntEbuyCrk0POJwbnYF1p0',
    appId: '1:248257115153:android:76e42d4b066ab245722db0',
    messagingSenderId: '248257115153',
    projectId: 'mechclient-bea53',
    databaseURL: 'https://mechclient-bea53-default-rtdb.firebaseio.com',
    storageBucket: 'mechclient-bea53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp0hQB3kqdjoYajAWIB_NBMQ0idnZAhnM',
    appId: '1:248257115153:ios:1861973d88fa96b7722db0',
    messagingSenderId: '248257115153',
    projectId: 'mechclient-bea53',
    databaseURL: 'https://mechclient-bea53-default-rtdb.firebaseio.com',
    storageBucket: 'mechclient-bea53.appspot.com',
    iosBundleId: 'cynex.net.mechClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp0hQB3kqdjoYajAWIB_NBMQ0idnZAhnM',
    appId: '1:248257115153:ios:4d6152c3c6fd78cc722db0',
    messagingSenderId: '248257115153',
    projectId: 'mechclient-bea53',
    databaseURL: 'https://mechclient-bea53-default-rtdb.firebaseio.com',
    storageBucket: 'mechclient-bea53.appspot.com',
    iosBundleId: 'cynex.net.mechClient.RunnerTests',
  );
}
